Create black jack construction 3.0 (completed) - no while loop to replay
This version is the completed version of blackjack but does not have a while loop to continue playing. 

error:  also there is still an error regarding the game starting sometimes and receiving and out of index error.